### ISSUE TITLE
RavenSharp is Depricated, needs to be updated to Sentry-Dotnet

### ISSUE THREAD

**Issue by DR9885** [olsh/serilog-sinks-sentry#21]
It looks like sentry has made a bunch of changes.

Deprecated: https://github.com/getsentry/raven-csharp
New: https://github.com/getsentry/sentry-dotnet

**Comment by olsh** [comment]
Hi @DR9885, there is an official Serilog integration.

https://www.nuget.org/packages/Sentry.Serilog
So this repo will be deprecated eventually.

**Comment by rogerfar** [comment]
Can this repo please be deprecated? I have spent an hour figuring out some random errors out in .NET Core 5, which eventually lead me to this ticket.

**Comment by olsh** [comment]
Hi @rogerfar,

There is a note at the top of the readme file.
https://github.com/olsh/serilog-sinks-sentry/blob/master/README.md

Also, I deprecated packages on NuGet.
https://www.nuget.org/packages/Serilog.Sinks.Sentry/
https://www.nuget.org/packages/Serilog.Sinks.Sentry.AspNetCore/

I think that we shouldn't archive the repo because it is still useful for projects older than the 4.6.1 framework.

Thank you for the suggestion! 👍🏻
