### ISSUE TITLE
New Verision with net6.0

### ISSUE THREAD

**Issue by antoinebou12** [olsh/serilog-sinks-sentry#29]
https://github.com/antoinebou12/Serilog.Sinks.SentrySDK

**Comment by olsh** [comment]
Hi @antoinebou12 

The library is not actively developed because there is an official library now
https://github.com/getsentry/sentry-dotnet

The only purpose of this library is legacy projects (.NET Framework 4.5 to 4.6.0)
https://github.com/serilog-contrib/serilog-sinks-sentry#note

Why don't you want to use the official library?

**Comment by antoinebou12** [comment]
Hi @olsh,

I want to use your serilog sinks features with only appsettings.json from microservice architecture

**Comment by olsh** [comment]
@antoinebou12 
You can do this with the official library, please check the example
https://github.com/getsentry/sentry-dotnet/tree/cb74dcde29d6e0430b2507ba72b35f2f486f2588/samples/Sentry.Samples.AspNetCore.Serilog
