### ISSUE TITLE
Warning NU1701 when use in asp.net core app

### ISSUE THREAD

**Issue by fisenkodv** [olsh/serilog-sinks-sentry#4]
I've got the following warning when added the sink
`
warning NU1701: Package 'Serilog.Sinks.Sentry 2.0.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
`

**Comment by olsh** [comment]
Hi @fisenkodv,
The sink uses [raven-csharp](https://github.com/getsentry/raven-csharp), and because of this [issue](https://github.com/getsentry/raven-csharp/issues/125), I cannot target the sink to .NET Standard.
When the issue will be resolved, I'll upgrade the target framework as well.
For now, you can ignore the warning, raven-csharp should work fine on .NET Core 2.x.

**Comment by olsh** [comment]
Version 2.1.2 was built agains net standard 2.0.

Feel free to reopen the issue if you have any problems.
